
services:
  hoanganh-mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver-HOANGANH
    restart: always
    hostname: mssql
    user: "root"
    environment:
      SA_PASSWORD: "Password123" 
      ACCEPT_EULA: "Y"
    volumes:
      - mssqlvolume:/var/opt/mssql/data
      - ./bk:/var/opt/mssql/backup 
    ports:
      - "1433:1433"

volumes:  
  mssqlvolume:
    name: sqlserver-HOANGANH-vl
